### ISSUE TITLE
Sentinel shadow entities

### ISSUE THREAD

**Issue by SlimeDog** [mcmonkeyprojects/Sentinel#296]
```
>version
[06:28:29] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-093165d-ba575a5 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
[06:28:29] [Server thread/INFO]: You are running the latest version
>version Citizens
[07:03:22] [Server thread/INFO]: Citizens version 2.0.25-SNAPSHOT (build 1700)
[07:03:22] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[07:03:22] [Server thread/INFO]: Authors: aPunch and fullwall
>version Sentinel
[06:29:29] [Server thread/INFO]: Sentinel version 1.9.2 (build 261)
[06:29:29] [Server thread/INFO]: Author: mcmonkey
```
[Sentinel/config.yml](http://blackdog.straight8.com/drops/sentinel-config.yml)

I have four Sentinel tame wolves and one Player NPC near the spawn point in a creative world (world). World was **--forceUpgrade** converted from 1.13.2. In 1.14.x, the Sentinels have acquired shadow wolf entities in the four locations, oriented per the Sentinel's positions (including yaw). The shadow entities
- do not move, even when their related Sentinels do (the Sentinels are busy chasing bats)
- do not move their heads, even to follow player movement, as normal NPC do
- do not appear in _Citizens/saves.yml_
- do not appear in the output of **npc list**
- appear in entity counts (for example, using **insights:scan**)
- can be seen with **data get**
- cannot be manipulated with **data merge**; although it reports success, their attributes are unchanged
- cannot be removed by means that I have been able to discover, even if I make the Sentinels vulnerable or despawn the Sentinels
- do not appear if the **Sentinel** plugin is disabled (the Sentinel NPCs remain, but they are no longer have the Sentinel trait, of course)

So the shadow entities are clearly tied to the Sentinel entities somehow.

After **citizens reload**, there are multiple shadow entities per Sentinel. All of them display the same names as the related Sentinels. As before, the shadow entitles do not appear in the output of **npc list**.

There are Sentinels in other (survival) worlds that do not acquire shadow entities.

The issue has been present since 1.14-pre1. I have rebuild the world several times since, but the issue always returns. The same NPC/Sentinel configuration worked without issues from 1.8.3 through 1.13.2, and is currently working correctly in 1.13.2.

Citizens/saves.yml for one of the four Sentinels; the others are similar, with different locations
```
npc:
  '1':
    name: Killer
    uuid: 57523cee-360d-4468-a0fa-46949dfbb3fe
    traits:
      spawned: true
      lookclose:
        enabled: true
        range: '5.0'
        realisticlooking: false
        enableRandomLook: false
        randomLookDelay: 60
      type: WOLF
      location:
        world: world
        x: '-14.5'
        y: '64.0'
        z: '-14.5'
        yaw: '-45.0'
        pitch: '0.0'
      waypoints:
        linear:
          points:
            '0':
              location:
                world: world
                x: '-14.5'
                y: '64.0'
                z: '-14.5'
                yaw: '-45.0'
                pitch: '0.0'
        provider: linear
      sentinel:
        stats_ticksSpawned: 82811973
        stats_timesSpawned: 9165
        stats_arrowsFired: 0
        stats_potionsThrow: 0
        stats_fireballsFired: 0
        stats_punches: 2981
        stats_attackAttempts: 178216
        stats_damageTaken: 8.841066865921022
        stats_damageGiven: 22940.97999984026
        range: 20.0
        damage: 10.0
        armor: -1.0
        health: 20.0
        ranged_chase: false
        close_chase: true
        invincible: true
        fightback: true
        attackRate: 30
        healRate: 30
        guardingUpper: 0
        guardingLower: 0
        needsAmmo: false
        safeShot: true
        respawnTime: 100
        chaseRange: 64.0
        enemyDrops: false
        enemyTargetTime: 0
        stats_snowballsThrown: 0
        stats_eggsThrown: 0
        stats_skullsThrown: 0
        stats_pearlsUsed: 0
        attackRateRanged: 30
        speed: 2.0
        greet_range: 10.0
        autoswitch: false
        accuracy: 0.0
        spawnPoint:
          world: world
          x: '-14.5'
          y: '64.0'
          z: '-14.5'
          yaw: '-45.0'
          pitch: '0.0'
        realistic: false
        reach: 3.0
        avoidRange: 10.0
        runaway: false
        guard_distance_minimum: 7.0
        guard_selection_range: 4.0
        allTargets:
          targets:
            '0': MONSTER
            '1': PASSIVE_MOB
        allIgnores:
          targets:
            '0': PLAYER
            '1': OWNER
      wolfmodifiers:
        angry: false
        collarColor: RED
        sitting: false
        tamed: true
      age:
        age: 0
        locked: true
      owner:
        owner: PLAYER_NAME_REDACTED
        uuid: PLAYER_UUID_REDACTED
    traitnames: owner,wolfmodifiers,type,location,lookclose,mounttrait,age,waypoints,sentinel,spawned,inventory
    navigator:
      stationaryticks: 100
      speedmodifier: '2.0'
      avoidwater: true
      usedefaultstuckaction: true
      pathfindingrange: '100.0'
      distancemargin: '1.5'
    metadata:
      protected: true
```

**Comment by SlimeDog** [comment]
If I change the Sentinels to cats
```
npc select Killer
npc type CAT
```
and restart the server, the shadow entities are not present. If I change the Sentinels back to wolves, the shadow entities reappear.

**Comment by SlimeDog** [comment]
Create non-Sentinel wolf NPC
```
npc create --type wolf
```
No shadow entities for that NPC. Restart the server. No shadow entities for that NPC.

**Comment by mcmonkey4eva** [comment]
```yml

      owner:
        owner: rambeau
        uuid: PLAYER_UUID_REDACTED
```
What's with the 'redacted' bit? You understand that UUIDs are public information, right? https://namemc.com/profile/rambeau.1

----

I'm having trouble replicating this. Running the exact same builds as in your opening post,
**Setup:**
`/npc create bob --type wolf`
`/npc wolf -t`
`/npc path` + set 1 point
`/npc lookclose`
`/npc inventory` (just to add the trait just in case as you have it set)
`/trait sentinel`
`/sentinel guard mcmonkey4eva` (to have it move away from it's starting point to better reveal dup entities)
`/sentinel invincible`
**Test:**
`/citizens save`
`/citizens reload`
move around a bit
just the one wolf here, no shadow.

---

My guess here is in the direction of potential plugin interference (the issue may only appear with some given other plugin installed) or world setting issue (a gamerule or similar that is required to cause it)

Can you please test for plugin conflicts? https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by SlimeDog** [comment]
Of course. I missed the second edit. Please redact my name.

**Comment by SlimeDog** [comment]
Add wolf modifiers to XYZZY
```
      wolfmodifiers:
        angry: false
        collarColor: RED
        sitting: false
        tamed: true
```
with the same result. No shadow entities.
